# Generated by Django 5.2.5 on 2025-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
