# Generated by Django 5.2.5 on 2025-08-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_session_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymclass',
            name='instructor',
        ),
    ]
